version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: 'redis:5-alpine'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'

  web:
    build: .
    command: bash -c "
      rails db:setup
      && rm -f tmp/pids/server.pid && ./bin/dev
      "
      # bundle install
    volumes:
      - .:/rails_app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    tty: true
    stdin_open: true
volumes:
  postgres:
  redis:
