version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: 'redis:5-alpine'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'

  web:
    build: .
    command: bash -c "
      bundle install
      && rails db:setup
      && rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'
      "
    volumes:
      - .:/rails_app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    tty: true
    stdin_open: true
volumes:
  postgres:
  redis:
