version: "3"
services:
  guessref_app:
    build: ./app
    container_name: guessref_app
    ports:
    - "3000:3000"
    volumes:
      - ./app:/app
    environment:
      REACT_APP_HASURA_WEBSOCKET_URL: ws://localhost:8080/v1/graphql
      REACT_APP_HASURA_REST_API: http://localhost:8080/api/rest
      REACT_APP_RAILS: http://localhost:3001

  postgres:
    image: postgres:12.6
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: guessref_development
    ports:
      - "5433:5432"
  hasura:
    image: "${HASURA_IMAGE:-hasura/graphql-engine:v2.0.0-beta.2}"
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    - "api"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:password@host.docker.internal:5433/guessref_development
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_ADMIN_SECRET: "secret"
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: "anonymous"
  api:
    build: ./api
    volumes:
      - ./api:/myapp
    ports:
      - "3001:3001"
    depends_on:
      - postgres
volumes:
  db_data:
