default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: postgres
  username: postgres
  password: password

development:
  <<: *default
  database: guessref_development

test:
  <<: *default
  database: guessref_test

production:
  <<: *default
  database: nargh_production
  username: nargh
  password: <%= ENV['NARGH_DATABASE_PASSWORD'] %>
